sudo: false
language: node_js
node_js:
- stable
addons:
  hosts:
  - platform.codecult.local
  - codecult.local
before_script:
- npm install -g bower grunt-cli
- bower install
- gem install compass
before_deploy:
- grunt
deploy:
  provider: heroku
  buildpack: ruby
  skip_cleanup: true
  api_key:
    secure: XiF+9kuIWpA8ryjNcRspLgbVYj9AMmrpB/mgzJWSW+khNon5icP2XJ0ip7sNJAcKsstV6frw4Sm6fQLuDYAPm8uMtDb+lx09do5gQG6ZvChukx4VYn5BCHFjWV8dLU0Z8FzQ4CTtSG2tvWT7aSapzPXrTWcsrcMaDV9wrUB7LxI0OmSURZEk1zzorZxeDSJfzxI9UoDE1oJGUdlcYNbpWKqc6aJOiyVkF8SdTtA0Y4kzsrlqtUS2osAoD0Bx85sVMRiM2vOZb9J2ETouYPc0jCZNKsPgbanH3ZywucZ6SKT7o85uRi9jOzEuag/V8ivGj5KvIE9L3YMnFmdFpCxheEnxk7ORfPqtIrOQRsn/SNwnkW+kkIke/D6fFGJojHupT3u4MWdtFigTZ7B1HRb3KdMPNDDSDrjcN3DUlUcEiWFnFWhyWyxqkMK1SVeXD6cgHBHH/H8Eip3+Igk03maItbg3iFqhK5fp1bfvmuNLxxwiYaqfINrtGPxeN3N+hiKc6cYf4CSlop0/02H9Lls35747w+hdtl5dyiUNSWNh4eE1tWk7CEw/stgUdec6HhTj090J533y6XbaCApKEwHZ+QiKfjXoUd0GUFIVjbXvlcVSUbWbvhN7LcBAAnCKsmj2lpDwQGruIsPMK0j3wqpHq+A2l3GB/V+Vu3fgaWKOpak=
  app: eduraam-frontend-staging
  on:
    branch: master
    repo: PerceptumNL/edubox-platform-frontend
